name: Release
on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.21'

    - name: Fetch all tags
      run: git fetch --tags

    - name: List all tags
      run: git tag

    - name: Generate Release Notes
      id: generate-notes
      run: |
        # Extract the current tag from the github ref (refs/tags/<tag_name>)
        CURRENT_TAG=${GITHUB_REF#refs/tags/}

        # Get the previous tag
        PREVIOUS_TAG=$(git tag --sort=-creatordate | awk 'NR==2')

        # Fetch commit messages between the two tags
        RELEASE_NOTES=$(git log $PREVIOUS_TAG..$CURRENT_TAG --pretty=format:"- %s%n")

        # Setting it as release notes
        echo "RELEASE_NOTES=$RELEASE_NOTES" >> $GITHUB_ENV

    - name: Build Binaries
      run: |
        GOOS=windows GOARCH=amd64 go build -o steelcut_windows_amd64.exe
        GOOS=darwin GOARCH=amd64 go build -o steelcut_darwin_amd64
        GOOS=linux GOARCH=amd64 go build -o steelcut_linux_amd64
        GOOS=darwin GOARCH=arm64 go build -o steelcut_darwin_arm64
        GOOS=linux GOARCH=arm64 go build -o steelcut_linux_arm64

    - name: Create GitHub Release
      run: |
        gh release create ${{ github.ref }} \
          steelcut_windows_amd64.exe \
          steelcut_darwin_amd64 \
          steelcut_linux_amd64 \
          steelcut_darwin_arm64 \
          steelcut_linux_arm64 \
          --title "Release ${{ github.ref }}" \
          --notes "${RELEASE_NOTES}"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
