name: Release
on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.21'

    - name: Build Binaries
      run: |
        GOOS=windows GOARCH=amd64 go build -o steelcut_windows_amd64.exe
        GOOS=darwin GOARCH=amd64 go build -o steelcut_darwin_amd64
        GOOS=linux GOARCH=amd64 go build -o steelcut_linux_amd64

    - name: Install GitHub CLI
      run: |
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
        sudo apt-add-repository https://cli.github.com/packages
        sudo apt update
        sudo apt install gh

    - name: Create GitHub Release
      run: |
        gh release create ${{ github.ref }} \
          steelcut_windows_amd64.exe \
          steelcut_darwin_amd64 \
          steelcut_linux_amd64 \
          --title "Release ${{ github.ref }}" \
          --notes "Release notes for ${{ github.ref }}"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
