name: Release
on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.21'

    - name: Generate Release Notes
      id: generate-notes
      run: |
        # Fetching commit messages since the last tag and setting it as release notes
        RELEASE_NOTES=$(git log $(git describe --tags --abbrev=0)..HEAD --pretty=format:"- %s")
        echo "RELEASE_NOTES=$RELEASE_NOTES" >> $GITHUB_ENV

    - name: Build Binaries
      run: |
        GOOS=windows GOARCH=amd64 go build -o steelcut_windows_amd64.exe
        GOOS=darwin GOARCH=amd64 go build -o steelcut_darwin_amd64
        GOOS=linux GOARCH=amd64 go build -o steelcut_linux_amd64
        GOOS=darwin GOARCH=arm64 go build -o steelcut_darwin_arm64
        GOOS=linux GOARCH=arm64 go build -o steelcut_linux_arm64

    - name: Create GitHub Release
      run: |
        gh release create ${{ github.ref }} \
          steelcut_windows_amd64.exe \
          steelcut_darwin_amd64 \
          steelcut_linux_amd64 \
          steelcut_darwin_arm64 \
          steelcut_linux_arm64 \
          --title "Release ${{ github.ref }}" \
          --notes "${RELEASE_NOTES}"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
