name: Release
on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.21'

    - name: Build Binaries
      run: |
        GOOS=windows GOARCH=amd64 go build -o steelcut_windows_amd64.exe
        GOOS=darwin GOARCH=amd64 go build -o steelcut_darwin_amd64
        GOOS=linux GOARCH=amd64 go build -o steelcut_linux_amd64

    - name: Create Release
      id: create_release
      uses: gh-actions/create-release@v1
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}

    - name: Upload Windows Asset
      uses: actions/upload-release-asset@v1.0.2
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./steelcut_windows_amd64.exe
        asset_name: steelcut_windows_amd64.exe
        asset_content_type: application/octet-stream

    - name: Upload Darwin Asset
      uses: actions/upload-release-asset@v1.0.2
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./steelcut_darwin_amd64
        asset_name: steelcut_darwin_amd64
        asset_content_type: application/octet-stream

    - name: Upload Linux Asset
      uses: actions/upload-release-asset@v1.0.2
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./steelcut_linux_amd64
        asset_name: steelcut_linux_amd64
        asset_content_type: application/octet-stream
